# Use Python 3.9 as base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy environment file and install dependencies
COPY environment.yml .
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/* \
    && pip install --no-cache-dir conda \
    && conda env create -f environment.yml \
    && conda clean -afy

# Copy application code
COPY . .

# Set environment variables
ENV PATH /opt/conda/envs/nlp_project/bin:$PATH
ENV PYTHONPATH /app

# Expose port 8000
EXPOSE 8000

## Command to serve the FASTAPI app
CMD ["conda", "run", "-n", "nlp_project", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]