# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'grpc_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12grpc_service.proto\x12\x05story\"-\n\x0cStoryRequest\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\r\n\x05theme\x18\x02 \x01(\t\"-\n\rStoryResponse\x12\r\n\x05story\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t2J\n\x0cStoryService\x12:\n\rGenerateStory\x12\x13.story.StoryRequest\x1a\x14.story.StoryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STORYREQUEST']._serialized_start=29
  _globals['_STORYREQUEST']._serialized_end=74
  _globals['_STORYRESPONSE']._serialized_start=76
  _globals['_STORYRESPONSE']._serialized_end=121
  _globals['_STORYSERVICE']._serialized_start=123
  _globals['_STORYSERVICE']._serialized_end=197
# @@protoc_insertion_point(module_scope)
